# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
encoding: utf-8
title: Botpress
description: An open-source, on-premises bot framework that saves thousands of developers thousands of hours.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://botpress.io/docs/" # the base hostname & protocol for your site
repository: /botpress/botpress/

permalink: /blog/:categories/:year/:month/:day/:title/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
flow:
  path: 'flow'

highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      footer: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      is_post: true

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - s3_website.yml
  - package.json
  - node_modules
  - .asset-cache
  - yarn.lock
  - config.ru
  - Procfile
  - Rakefile
  - vendor
  - Makefile
  - blog

assets:
  sources:
    - _assets/css
    - _assets/js
    - _assets/images
    - _assets/third-party
    - node_modules

include:
  - images

plugins:
  - algoliasearch-jekyll
